name: 'complexwebq'
data_folder: 'datasets/complexwebq/'
train_data: 'train.json'
dev_data: 'dev.json'
test_data: 'test.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities_v2.txt'
word_emb_file: "word_emb_100d.npy"
entity_emb_file: #"entity_emb_100d.npy"
entity_kge_file: #"entity_kge_100d.npy"
relation_emb_file: #"birelation_emb_100d.npy"
relation_kge_file: #"relation_kge_100d.npy"

to_save_model: True
save_model_file: "model/complexwebq/best_model_hybrid_trial1_1"
pred_file: "model/complexwebq/pred_hybrid"
load_model_file: #"model/complexwebq/best_model_hybrid"

# graph options
fact_dropout: 0.1
use_kb: True
use_doc: False

num_layer: 3
max_query_word: 10
max_document_word: 50

entity_dim: 25
word_dim: 100
kge_dim: 100
pagerank_lambda: 0.8
fact_scale: 3
use_inverse_relation: True

# optimization
num_epoch: 20
batch_size: 16
gradient_clip: 1
learning_rate: 0.003
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False


