name: 'metaqa'
data_folder: 'datasets/metaqa/3hop/'
train_data: 'train_out.json'
train_documents: #'documents.json'
dev_data: 'dev_out.json'
dev_documents: #'documents.json'
test_data: 'test_out.json'
test_documents: #'documents.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities.txt'
word_emb_file: null 
entity_emb_file: null 
entity_kge_file: null 
relation_emb_file: null 
relation_kge_file: null 

to_save_model: True
save_model_file: "model/wikimovie/best_metaqa3_%d_model"
pred_file: "model/wikimovie/pred_doc"
load_model_file: "model/wikimovie/best_metaqa3_%d_model"

# graph options
fact_dropout: 0.0
use_kb: True
use_doc: False

num_layer: 3
max_query_word: 10
max_document_word: 40

entity_dim: 80
word_dim: 80
kge_dim: 80
pagerank_lambda: 0.8
fact_scale: 1
use_inverse_relation: True

# optimization
num_epoch: 80
batch_size: 80
gradient_clip: 1
learning_rate: 0.001
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False


