name: 'complexwebq'
data_folder: 'datasets/simpleq/'
train_data: 'train.json'
dev_data: 'dev.json'
test_data: 'test.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities_v2.txt'
word_emb_file: "word_emb_300d.npy"
entity_emb_file: #"entity_emb_100d.npy"
entity_kge_file: #"entity_kge_100d.npy"
relation_emb_file: "relation_emb_300d.npy"
relation_kge_file: #"relation_kge_100d.npy"
fact_data: "datasets/simpleq/facts.json"
eod: 0

to_save_model: True
save_model_file: "model/complexwebq/best_model_hybrid2"
pred_file: "model/complexwebq/pred_hybrid"
load_model_file: "model/complexwebq/best_model_hybrid"
save_fpnet_model_file: "model/simpleq/best_relreasoner_decoder"
load_fpnet_model_file: #"model/complexwebq/best_relreasoner_14_3"
save_entity_model_file: #"model/complexwebq/best_relreasoner_entity.1"
load_entity_model_file:

# graph options
fact_dropout: 0.1
use_kb: True
use_doc: False

num_layer: 3
max_query_word: 20
max_document_word: 50
num_hop: 1

entity_dim: 300
word_dim: 300
kge_dim: 25
pagerank_lambda: 0.8
fact_scale: 3
use_inverse_relation: False

# optimization
num_epoch: 150
batch_size: 80
test_batch_size: 20
gradient_clip: 1
learning_rate: 0.0001
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False


